//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputActions/AvatarInputActionsControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @AvatarInputActionsControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @AvatarInputActionsControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""AvatarInputActionsControls"",
    ""maps"": [
        {
            ""name"": ""Lamniat_Land"",
            ""id"": ""e6cae321-99e0-4375-9af9-b361da1455b9"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""d7dae9ef-466c-4c54-b9af-aa3128023eb4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Melee"",
                    ""type"": ""Button"",
                    ""id"": ""67a225ed-aba2-4b08-87d6-e2d237e90afd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AimAt_GamePad"",
                    ""type"": ""Value"",
                    ""id"": ""1e1d2e9c-c7ef-4d9a-a086-0cb56a80eac6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AimAt_Mouse"",
                    ""type"": ""PassThrough"",
                    ""id"": ""40e970ca-1182-46b0-bae9-c030fe413930"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""e4f158bd-0943-47d2-aae3-1f6120e006a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot_Hold"",
                    ""type"": ""Button"",
                    ""id"": ""f51a8b44-2005-4981-a956-62c676fa7be8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dodge"",
                    ""type"": ""Button"",
                    ""id"": ""cfaf3ca6-4058-4326-adc1-b9b6d097ef6a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7ebe0b2a-7f7f-49b7-abd9-982a6bdaed62"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Dodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9be91d66-dae0-4dec-9803-d644b656f66a"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Dodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0db6e1d9-ddfd-49d6-a481-97538f4ecf8e"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e49afdd8-c8ac-4fbc-b362-7e4f3240edde"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1245c265-16ad-439c-96fc-ef4bccb89105"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Shoot_Hold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ed3e5b5-81a3-400f-b7f4-9326f3a3cf77"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Shoot_Hold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5f114be-2e9a-4fc5-8e76-c55b831646cc"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""AimAt_Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1f1e5c2-a43a-4c70-b6f7-28c4be641e98"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AimAt_GamePad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""8DirectionalStick"",
                    ""id"": ""61378b33-e958-4122-bd6e-550b5dc0e3f0"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3f6fa3a2-473f-4910-b700-45a94c048983"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""199cd84e-fc96-4fcd-a355-bf8504703fd1"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""74fe5ee3-f5ed-4f48-b98f-7e9708b61151"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""db437aa4-4c94-4dae-841f-6bce0ee83b74"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""WASD Keys"",
                    ""id"": ""74ffdcd3-ec63-4e69-a8a2-430a473def7e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f67279cf-42eb-4ec0-947a-d8a920c47db0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9b58dc2b-4479-4ce2-bb5d-5fbd471bb40b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1b34e6f7-5054-462e-a7fc-8afd0e71ec8e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""96ecc255-c5eb-42e5-8a2e-d66728c61b75"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6a07de5e-37da-43cf-9f3a-b0843043d8f0"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Melee"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43869e2d-e0c6-4b33-96c4-43df5b538096"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Melee"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard & Mouse"",
            ""bindingGroup"": ""Keyboard & Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Lamniat_Land
        m_Lamniat_Land = asset.FindActionMap("Lamniat_Land", throwIfNotFound: true);
        m_Lamniat_Land_Move = m_Lamniat_Land.FindAction("Move", throwIfNotFound: true);
        m_Lamniat_Land_Melee = m_Lamniat_Land.FindAction("Melee", throwIfNotFound: true);
        m_Lamniat_Land_AimAt_GamePad = m_Lamniat_Land.FindAction("AimAt_GamePad", throwIfNotFound: true);
        m_Lamniat_Land_AimAt_Mouse = m_Lamniat_Land.FindAction("AimAt_Mouse", throwIfNotFound: true);
        m_Lamniat_Land_Shoot = m_Lamniat_Land.FindAction("Shoot", throwIfNotFound: true);
        m_Lamniat_Land_Shoot_Hold = m_Lamniat_Land.FindAction("Shoot_Hold", throwIfNotFound: true);
        m_Lamniat_Land_Dodge = m_Lamniat_Land.FindAction("Dodge", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Lamniat_Land
    private readonly InputActionMap m_Lamniat_Land;
    private List<ILamniat_LandActions> m_Lamniat_LandActionsCallbackInterfaces = new List<ILamniat_LandActions>();
    private readonly InputAction m_Lamniat_Land_Move;
    private readonly InputAction m_Lamniat_Land_Melee;
    private readonly InputAction m_Lamniat_Land_AimAt_GamePad;
    private readonly InputAction m_Lamniat_Land_AimAt_Mouse;
    private readonly InputAction m_Lamniat_Land_Shoot;
    private readonly InputAction m_Lamniat_Land_Shoot_Hold;
    private readonly InputAction m_Lamniat_Land_Dodge;
    public struct Lamniat_LandActions
    {
        private @AvatarInputActionsControls m_Wrapper;
        public Lamniat_LandActions(@AvatarInputActionsControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Lamniat_Land_Move;
        public InputAction @Melee => m_Wrapper.m_Lamniat_Land_Melee;
        public InputAction @AimAt_GamePad => m_Wrapper.m_Lamniat_Land_AimAt_GamePad;
        public InputAction @AimAt_Mouse => m_Wrapper.m_Lamniat_Land_AimAt_Mouse;
        public InputAction @Shoot => m_Wrapper.m_Lamniat_Land_Shoot;
        public InputAction @Shoot_Hold => m_Wrapper.m_Lamniat_Land_Shoot_Hold;
        public InputAction @Dodge => m_Wrapper.m_Lamniat_Land_Dodge;
        public InputActionMap Get() { return m_Wrapper.m_Lamniat_Land; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Lamniat_LandActions set) { return set.Get(); }
        public void AddCallbacks(ILamniat_LandActions instance)
        {
            if (instance == null || m_Wrapper.m_Lamniat_LandActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Lamniat_LandActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Melee.started += instance.OnMelee;
            @Melee.performed += instance.OnMelee;
            @Melee.canceled += instance.OnMelee;
            @AimAt_GamePad.started += instance.OnAimAt_GamePad;
            @AimAt_GamePad.performed += instance.OnAimAt_GamePad;
            @AimAt_GamePad.canceled += instance.OnAimAt_GamePad;
            @AimAt_Mouse.started += instance.OnAimAt_Mouse;
            @AimAt_Mouse.performed += instance.OnAimAt_Mouse;
            @AimAt_Mouse.canceled += instance.OnAimAt_Mouse;
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
            @Shoot_Hold.started += instance.OnShoot_Hold;
            @Shoot_Hold.performed += instance.OnShoot_Hold;
            @Shoot_Hold.canceled += instance.OnShoot_Hold;
            @Dodge.started += instance.OnDodge;
            @Dodge.performed += instance.OnDodge;
            @Dodge.canceled += instance.OnDodge;
        }

        private void UnregisterCallbacks(ILamniat_LandActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Melee.started -= instance.OnMelee;
            @Melee.performed -= instance.OnMelee;
            @Melee.canceled -= instance.OnMelee;
            @AimAt_GamePad.started -= instance.OnAimAt_GamePad;
            @AimAt_GamePad.performed -= instance.OnAimAt_GamePad;
            @AimAt_GamePad.canceled -= instance.OnAimAt_GamePad;
            @AimAt_Mouse.started -= instance.OnAimAt_Mouse;
            @AimAt_Mouse.performed -= instance.OnAimAt_Mouse;
            @AimAt_Mouse.canceled -= instance.OnAimAt_Mouse;
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
            @Shoot_Hold.started -= instance.OnShoot_Hold;
            @Shoot_Hold.performed -= instance.OnShoot_Hold;
            @Shoot_Hold.canceled -= instance.OnShoot_Hold;
            @Dodge.started -= instance.OnDodge;
            @Dodge.performed -= instance.OnDodge;
            @Dodge.canceled -= instance.OnDodge;
        }

        public void RemoveCallbacks(ILamniat_LandActions instance)
        {
            if (m_Wrapper.m_Lamniat_LandActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILamniat_LandActions instance)
        {
            foreach (var item in m_Wrapper.m_Lamniat_LandActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Lamniat_LandActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Lamniat_LandActions @Lamniat_Land => new Lamniat_LandActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard & Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface ILamniat_LandActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnMelee(InputAction.CallbackContext context);
        void OnAimAt_GamePad(InputAction.CallbackContext context);
        void OnAimAt_Mouse(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnShoot_Hold(InputAction.CallbackContext context);
        void OnDodge(InputAction.CallbackContext context);
    }
}
